Fix duplication in error message
After changing the commands' function to return an error (use `RunE` instead of `Run`), when an error occurred, the error message was printed twice, for example:
```
→ ./bin/flotta delete device -n device1
Unregister failed: edgedevices.management.project-flotta.io "device1" not found
Error: edgedevices.management.project-flotta.io "device1" not found
```

Signed-off-by: arielireni <aireni@redhat.com>